fix: Add missing env var to set log shipping lambda
Resovles this error message seen in the logs of the set log shipping lambda:

```log
Error: Missing ENV var LOG_KINESIS_STREAM
```