refactor: Move to NPM workspaces
This is after seeing this message when running tests:

```log
error TS6059: File '/Users/akash_askoolum/code/cloudwatch-logs-management/cdk/bin/cdk.ts' is not under 'rootDir' '/Users/akash_askoolum/code/cloudwatch-logs-management/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by include pattern '**/*' in '/Users/akash_askoolum/code/cloudwatch-logs-management/tsconfig.json'

error TS6059: File '/Users/akash_askoolum/code/cloudwatch-logs-management/cdk/lib/cloudwatch-logs-management.test.ts' is not under 'rootDir' '/Users/akash_askoolum/code/cloudwatch-logs-management/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Matched by include pattern '**/*' in '/Users/akash_askoolum/code/cloudwatch-logs-management/tsconfig.json'

Found 2 errors.
```